name: a-motivational-quote

services:
    a-motivational-quote-db:
        image: mysql
        restart: always
        container_name: a-motivational-quote-db
        hostname: a-motivational-quote-db
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            a-motivational-quote:
                aliases:
                - mysql

    web:
        image: node
        container_name: a-motivational-quote-api
        working_dir: /home/node/app
        ports:
            - '4000:4000'
        expose:
            - 4000
        environment:
            NODE_ENV: development
            DB_HOST: a-motivational-quote-db
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            SEED_LIMIT: 500
        volumes:
            - ./:/home/node/app
        restart: always
        entrypoint: ["/bin/bash", "/home/node/app/docker-entrypoint.sh"]
        links:
            - a-motivational-quote-db
        depends_on:
            - a-motivational-quote-db
        networks:
            a-motivational-quote:
                aliases:
                - web

networks:
  a-motivational-quote:
    driver: bridge